name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Build Release
        run: cargo build --release

      - name: Rename executable
        run: Move-Item -Path "target/release/lexi.exe" -Destination "target/release/LEXI.exe"

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: target/release/LEXI.exe
